// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYt4iOvx-qJGHly5Ej62cDpckHqeI4jdc',
    appId: '1:659169980743:web:57321dcd02aa22e04c5c62',
    messagingSenderId: '659169980743',
    projectId: 'chat-app-8a57f',
    authDomain: 'chat-app-8a57f.firebaseapp.com',
    storageBucket: 'chat-app-8a57f.appspot.com',
    measurementId: 'G-WJSG4TPPDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh9GSr8qVvIk_U281MVYdtP8-jH-_ZDpA',
    appId: '1:659169980743:android:c9efd69871d1b4c24c5c62',
    messagingSenderId: '659169980743',
    projectId: 'chat-app-8a57f',
    storageBucket: 'chat-app-8a57f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVYUJeDS9inp1BxNZgIeXF0zDpH6ZioYI',
    appId: '1:659169980743:ios:4e96d1b57cd898134c5c62',
    messagingSenderId: '659169980743',
    projectId: 'chat-app-8a57f',
    storageBucket: 'chat-app-8a57f.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVYUJeDS9inp1BxNZgIeXF0zDpH6ZioYI',
    appId: '1:659169980743:ios:4e96d1b57cd898134c5c62',
    messagingSenderId: '659169980743',
    projectId: 'chat-app-8a57f',
    storageBucket: 'chat-app-8a57f.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYt4iOvx-qJGHly5Ej62cDpckHqeI4jdc',
    appId: '1:659169980743:web:3a3e3d6c932118424c5c62',
    messagingSenderId: '659169980743',
    projectId: 'chat-app-8a57f',
    authDomain: 'chat-app-8a57f.firebaseapp.com',
    storageBucket: 'chat-app-8a57f.appspot.com',
    measurementId: 'G-9H0KCJ2H4M',
  );
}